// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class migration_contentstatusadd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration_contentstatusadd));
        
        string IMigrationMetadata.Id
        {
            get { return "202511142157329_migration_contentstatusadd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
